### ISSUE TITLE
Cleanup group module code structure and migrate new repo layout

### ISSUE THREAD

**Issue by clevinson** [regen-network/cosmos-modules#25]
As discussed in the call we do not push the changes downstream into the [cosmos/modules](https://github.com/cosmos/modules). This becomes an independent fork.

**Comment by clevinson** [comment]
@aaronc can this be closed/merged?

**Comment by clevinson** [comment]
We still have some pending tasks in the PR, but @alpe suggests we merge as is, and tackle those later as separate tickets.

**Comment by aaronc** [comment]
#28 is still in draft mode. Please mark it R4R if it's ready @alpe and then I'll take a look and try to get it merged quickly.
