### ISSUE TITLE
Add UInt64Index

### ISSUE THREAD

**Issue by aaronc** [regen-network/cosmos-modules#5]
A `UInt64Index` would basically take the interface from `AutoUInt64Table` and abstract it to an index:

```go
type UInt64Index interface {
	Has(ctx HasKVStore, key uint64) bool
	Get(ctx HasKVStore, key uint64) (Iterator, error)
	PrefixScan(ctx HasKVStore, start, end uint64) (UInt64Iterator, error)
	ReversePrefixScan(ctx HasKVStore, start, end uint64) (UInt64Iterator, error)
}

type UInt64Iterator interface {
         LoadNext(dest interface{}) (key uint64, err error)
         io.Closer    
}
```

with a constructor along the lines of:
```go
NewUInt64Index(builder Indexable, prefix byte, indexer UInt64IndexerFunc)
```

**Comment by alpe** [comment]
Do I understand this correct that this is a new typed secondary index? Can we make assumptions that `UInt64IndexerFunc` is a multiKey?

**Comment by aaronc** [comment]
Yes and yes. Basically the equivalent of `Index` for `uint64`.

**Comment by aaronc** [comment]
Regarding your comment offline about `UInt64Iterator` being incompatible with the existing `Iterator`. Would there be any benefit to doing something like this:

```go
type Iterator interface {
         Next() error
         LoadCurrent(dest interface{}) (key []byte)
         io.Closer    
}

type UInt64Iterator {
       Iterator
       LoadCurrentUInt64(dest interface{}) (key uint64)
}
```

I'm not attached to this particular design, I'm just wondering if there's anywhere something like this would be useful. In particular, maybe for `AutoUInt64Table` so there's some way to get the `uint64` key back without having to parse `[]byte` to `uint64`. What do you think?

**Comment by alpe** [comment]
> Would there be any benefit to doing something like this: ...

I found the []byte representation of the RowID useful in tests. Not sure if this is true if I would use it from other packages but with the planned refactorings on natural key tables the []byte slice is compatible.
if there would be any other good way to get the RowID I would even drop the return parameter here.

What I definitively like is the clean and minimalistic iterator interface.  A `UInt64Iterator` can be an Adapter to this:
```go
it, _ := store.Get(ctx, myKey)
newIt := UInt64Iterator(it)
```
Current Iterator helper functions `LimitIterator`, `First`, `ReadAll` would be incompatible though

**Comment by aaronc** [comment]
The adapter approach looks interesting, however the index does know its actual key type and with that approach it's up to the user.

I understand the concern about iterator helper functions. That's why I was attempting a design that had `UInt64Iterator` extend `Iterator`. An alternative is to create helper functions for every typed iterator, but maybe that's too complex. In my mind this problem begs for generics. Anyway... let's discuss this live a bit. I need to think about what might be best.

**Comment by alpe** [comment]
> however the index does know its actual key type ...

UInt64Indexes can be used with NaturalKey, AutoUint64 and also ExternalTables. The `[]byte` slice returned by the `Iterator.LoadNext()` is the `RowID` under which the object is stored in the table and not in the index. The full Index prefix key used for the index is not [exposed](https://github.com/regen-network/cosmos-modules/blob/orm_develop/incubator/orm/index.go#L159) (neither old or new impl)

**Comment by aaronc** [comment]
Okay, so seems like the plain `Iterator` actually makes sense then because the underlying index search key isn't exposed. So we'll just leave it as is. I think this is done so closing.
